added some helpful instructions for linking .local/bin to PATH in .bashrc

diff --git a/install b/install
--- a/install
+++ b/install
@@ -10,3 +10,10 @@ if [ $? -ne 0 ]; then
     echo "Install failed"
     exit 1
 fi
+
+which starsmashertools &>/dev/null
+if [ $? -ne 0 ]; then
+    echo "Warning: cannot find command 'starsmashertools'"
+    echo "To complete your installation add the following line to $HOME/.bashrc:"
+    echo 'export PATH="$HOME/.local/bin:$PATH"'
+fi
diff --git a/install_offline b/install_offline
--- a/install_offline
+++ b/install_offline
@@ -1,3 +1,10 @@
 #!/bin/bash
 
 python3 -m pip install --no-build-isolation -e .
+
+which starsmashertools &>/dev/null
+if [ $? -ne 0 ]; then
+    echo "Warning: cannot find command 'starsmashertools'"
+    echo "To complete your installation add the following line to $HOME/.bashrc:"
+    echo 'export PATH="$HOME/.local/bin:$PATH"'
+fi
